### ISSUE TITLE
Dynamic Height Jquery Steps

### ISSUE THREAD

**Issue by nurmanhabib** [amteknologi/elearning#172]
Tampilan jQuery Steps waktu Tambah Kelas di modul Kelas Online dibuat dinamis untuk height-nya, sehingga user tidak susah mencari tombol Next.

![firefox_screenshot_2015-12-23t13-07-43 966z](https://cloud.githubusercontent.com/assets/5308494/11977014/09c35816-a9b1-11e5-929c-b6551fa69a07.png)

**Comment by singgihsap** [comment]
sudah mas @nurmanhabib di #204

**Comment by nurmanhabib** [comment]
sebenarnya yg saya maksud sih bukan overflow, tp heightnya mengikuti content, tapi kemarin masih kesulitan ya.. itu cm opsional aja sih utk tampilan

**Comment by candrawaskito** [comment]
kalau belum bener di reopen lagi aja @nurmanhabib
