### ISSUE TITLE
Forum : Approve Thread 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#173]
yang berhak approve thread adalah tenaga ahli yang mengelola kategori. @radhianPrayogo

**Comment by radhianPrayogo** [comment]
bisa di kasih screenshotnya nggak mbak @fadlillahayu ? aku bingung itu approve yang dimana

**Comment by radhianPrayogo** [comment]
sudah diperbaiki di commitan #167 , coba di pull ulang dan di test lagi

**Comment by fadlillahayu** [comment]
thread dan topic yang belum diapprove tidak muncul dihalaman depan forum.
toipic yang belum diapprove tidak bisa ditambahin threadnya dan tidak bisa dicomment
@radhianPrayogo

**Comment by fadlillahayu** [comment]
oke yang ini juga sudah
