### ISSUE TITLE
Forum Notifikasi

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#174]
notifikasi sukses pada thread ataupun topik yang disetujui warnanya dibedakan dari warna dominan agar mudah terlihat. @singgihsap  @radhianPrayogo

**Comment by singgihsap** [comment]
mba @fadlillahayu ini bagian warna notif succes dibedakan sesuai dengan button ya ?

**Comment by fadlillahayu** [comment]
dibedakan dengan buttonnya @singgihsap

**Comment by singgihsap** [comment]
mba udah tak benerin di #198

**Comment by candrawaskito** [comment]
oke sip

**Comment by fadlillahayu** [comment]
mas @candrawaskito ini dari @radhianPrayogo nya belum diperbaiki, jadi di sistemnya belum keganti.. jangan dulu diclose.

**Comment by fadlillahayu** [comment]
@radhianPrayogo yang ini jangan lupa diperbaiki.
