### ISSUE TITLE
Forum Navbar Thread

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#175]
Navbar thread pada hamalan approve tidak ada, harusnya ada @radhianPrayogo

**Comment by radhianPrayogo** [comment]
tolong di kasih screenshootnya mbak @fadlillahayu

**Comment by fadlillahayu** [comment]
![thread hilang](https://cloud.githubusercontent.com/assets/16182401/12013147/3b3af3a0-ad43-11e5-91e6-f8f8db447e6c.png)

**Comment by radhianPrayogo** [comment]
yang di halaman edit & create dikasih juga nggak mbak @fadlillahayu ?

**Comment by candrawaskito** [comment]
yups di kasih juga @radhianPrayogo

**Comment by radhianPrayogo** [comment]
oke, nunggu yg modul elib di merge dulu mas @candrawaskito , aku mau ngepullnya per modul soale

**Comment by candrawaskito** [comment]
oh yang pull request ini ya #229 , oke nunggu confirm dari @nurmanhabib

**Comment by radhianPrayogo** [comment]
iya mas @candrawaskito , oke sip

**Comment by radhianPrayogo** [comment]
#238 udah diperbaiki mbak @fadlillahayu

**Comment by fadlillahayu** [comment]
oke, yang ini sudah @radhianPrayogo
