### ISSUE TITLE
Portal Halaman Admin

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#177]
Editor tidak bia mengakses kategori artikel @nurmanhabib

**Comment by nurmanhabib** [comment]
bisa diperjelas, ini maksudnya seharusnya editor tidak bisa akses kategori atau saat ini editor tidak bisa akses? @fadlillahayu

**Comment by fadlillahayu** [comment]
editor seharusnya tidak bisa mengakses halaman kategori @nurmanhabib

**Comment by nurmanhabib** [comment]
sudah diperbaiki, silahkan coba lagi yaa.. kalo sudah benar silahkan di Close aja issue ini @fadlillahayu
