### ISSUE TITLE
Portal : Artikel Komentar

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#178]
Komentar belum tampil/masuk kehalaman admin @nurmanhabib

**Comment by nurmanhabib** [comment]
@fadlillahayu udah tak perbaiki mbak, klo dah normal jgn lupa di close yaa

**Comment by fadlillahayu** [comment]
reply commentarnya blm bisa diklik bib..
![reply comentar](https://cloud.githubusercontent.com/assets/16182401/12013400/5ee183e6-ad48-11e5-90a9-5cf4359d7e26.png)

**Comment by fadlillahayu** [comment]
kalo bisa untuk reply pos, kelika klik tombol reply muncul kolom dibawah commentar untuk post reply commentar @nurmanhabib

**Comment by candrawaskito** [comment]
gak usah di munculin di bawah post reply, kebanyakan jquery berat, di direct ke form yang atas nya aja, kan sama aja.

**Comment by nurmanhabib** [comment]
@candrawaskito mgkin ditambahkan keterangan klo itu posisi mau ngereply siapa gitu

**Comment by candrawaskito** [comment]
ya gt juga boleh, yg penting direct langsung aja ke form atasnya. Biar simple

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah diperbaiki #291
