### ISSUE TITLE
Portal : Error Link Kirim Artikel 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#180]
error link ketika memilih button kirim artikel dihalaman public : http://localhost/elearning/submitarticle @nurmanhabib

**Comment by nurmanhabib** [comment]
@fadlillahayu mungkin kalo kasus gini bisa screenshoot, aku belum paham :D Error nya kayak gmn

**Comment by fadlillahayu** [comment]
ini sudah bisa @nurmanhabib , tak coba lagi sudah gak nemu errornya.
