### ISSUE TITLE
Portal : Update Kategori Artikel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#182]
kategori gagal update atau tidak bisa update kategori : http://localhost/elearning/admin/kategori/update/2 dan error link ketika memilih button update kategori : http://localhost/elearning/admin/kategori/update @nurmanhabib

**Comment by nurmanhabib** [comment]
@fadlillahayu mbak ini udah tak perbaiki, cuma salah redirect aja tadi
