### ISSUE TITLE
Portal : Tambah Artikel dihalaman Admindan Editor

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#183]
ketika membuat artikel dan menambahkan Carousel Slider dan Featured Image, seharusnya Carousel Slider dan Featured Image ada previewnya : http://localhost/elearning/admin/article/add @nurmanhabib

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah diperbaiki #294

**Comment by fadlillahayu** [comment]
@nurmanhabib ini kalo ditekan tombol cancel kok gambarnya gak hilang ya?
![abc](https://cloud.githubusercontent.com/assets/16182401/12105590/bb2a4b7e-b388-11e5-9568-87d7677ecc77.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah bisa cancel di #298
