### ISSUE TITLE
Portal : Featured Image Halaman Publik

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#185]
ketika berhasil menambahkan Featured image, dikasih preview imagenya 
![addartikelprivate](https://cloud.githubusercontent.com/assets/16182401/11988196/65862bf2-aa1e-11e5-8d07-d6d4739ce35e.png) @nurmanhabib

**Comment by nurmanhabib** [comment]
@fadlillahayu ini udah lama diperbaiki lo

**Comment by fadlillahayu** [comment]
lupa close @nurmanhabib
