### ISSUE TITLE
Butuh informasi ukuran width dan height gambar

### ISSUE THREAD

**Issue by nurmanhabib** [amteknologi/elearning#189]
@fajarekos saya butuh segera untuk ukuran fix pada beberapa gambar:

1. Gambar slider di halaman portal index
2. Gambar featured di single portal
3. Gambar avatar user
4. Jika ada gambar lain, silahkan sertakan

```
<img src="images/gambar.png" width=? height=?>
```

**Comment by fajarekos** [comment]
1. slider halaman portal : height: 332px, width: 746px
2. Gambar featured : width 623 height 302
3. avatar : 35 x 35px
semetara itu
