### ISSUE TITLE
konsultasi : tambahan text editor 

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#193]
tambahan text editor pada pertanyaan dan balas komentar @ahsansandiah

**Comment by nurmanhabib** [comment]
@YeyenMPJ mbak maksudnya dikasih text editor di pertanyaan yg mana ya? bisa diperjelas?

**Comment by YeyenMPJ** [comment]
![pertanyaan](https://cloud.githubusercontent.com/assets/16249496/12014950/e8cc7d90-ace9-11e5-87a9-6468e6016ab7.png) 

![balas](https://cloud.githubusercontent.com/assets/16249496/12014957/f988849e-ace9-11e5-8305-110fbbf9524c.png)

ini @nurmanhabib

**Comment by ahsansandiah** [comment]
udah ditambahin text editor #201 
tinggal nunggu marged.

**Comment by YeyenMPJ** [comment]
oke @ahsansandiah

**Comment by ahsansandiah** [comment]
oh maksud ku itu. #201 itu push an ku yen. yang udah diperbaharui
dan #193 itu kan issue mu. iya nggak toh :dancer:

**Comment by YeyenMPJ** [comment]
oooo yaaaa :smile_cat:

**Comment by nurmanhabib** [comment]
@ahsansandiah coba liat hasil yg udah dikasih tinymce

**Comment by YeyenMPJ** [comment]
oke sudah fix
