### ISSUE TITLE
Portal : Single Page

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#194]
ini category apa ya? @fajarekos @nurmanhabib @candrawaskito 
![untitledcategory apa](https://cloud.githubusercontent.com/assets/16182401/12013439/438abe5e-ad49-11e5-9fb1-1a421060f66d.jpg)

**Comment by nurmanhabib** [comment]
@fadlillahayu oh itu sebenarnya konsep related post / artikel yang berhubungan. Tapi artikelnya pas ga diisi kategorinya jadinya no category...

**Comment by fadlillahayu** [comment]
oh.. udah @nurmanhabib
