### ISSUE TITLE
Portal : Kategori Artikel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#195]
Ketika create kategori harus memilih editor, jika editor tidak diisi maka kategori harusnya gagal dibuat. @nurmanhabib

**Comment by candrawaskito** [comment]
issue2 kayak gini harusnya udah di create minggu kemarin, kalau baru di create sekarang kapan mau di kerjainnya?

**Comment by fadlillahayu** [comment]
tambahan untuk kategori artikel : untuk artikel yang memiliki kategori yang dikelola oleh editor 1 tidak terlihat pada list artikel draf ataupun terbit pada editor 2, begitu juga sebaliknya.

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah diperbaiki pada #291
