### ISSUE TITLE
Elib : Gagal Edit Kategori 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#214]
gagal edit untuk kategori elib @ahsansandiah @radhianPrayogo 
![fireshot screen capture 042 - - localhost_elearning_admin_elibrary_category_edit_5](https://cloud.githubusercontent.com/assets/16182401/12033028/4601771e-ae51-11e5-8451-bb0519b250e4.png)

**Comment by ahsansandiah** [comment]
itu karna kamu belum buat folder "media" di (app/files/elibrary) jadi pas ngecreate kategori nggak sekalian kebuat folder kategori nya

aku udah perbaiki itu sekalian sudah ku cantumin file .gitignore nya. tapi belum di marged

**Comment by candrawaskito** [comment]
@ahsansandiah emang folder media itu harus setiap orang yang pull harus buat sendiri yah, kenapa di buat folder media default nya, jadi harus nya otomatis, atau ketika upload otomatis langsung create folder "media" gak semua user tau <code> atau yang berhubungan dengan development, untuk masalah merged itu kayaknya ada comment dari habib, dibiasakan dibales ya. #216

**Comment by candrawaskito** [comment]
ini juga, dibiasakan jangan di mention kalau untuk issue yang personal, di assign saja dan di kasih label @fadlillahayu 

<img width="269" alt="screen shot 2015-12-30 at 10 12 51 am" src="https://cloud.githubusercontent.com/assets/4866343/12045861/8c21273e-aede-11e5-8f8d-e210621e40b2.png">

**Comment by fadlillahayu** [comment]
oke yang ini sudah diperbaiki
