### ISSUE TITLE
ELib : Gagal Upload Media

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#220]
error waktu start di upload media admin @ahsansandiah 
![fireshot screen capture 047 - submit i elibrary - localhost_elearning_admin_elibrary_submit](https://cloud.githubusercontent.com/assets/16182401/12045664/4bdb89b6-aeda-11e5-99be-26a9ba31fe11.png)

**Comment by fadlillahayu** [comment]
ini link errornya : http://localhost/elearning/admin/elibrary/submit 
dan keterangan full errornya
![elib upload media](https://cloud.githubusercontent.com/assets/16182401/12045714/70f7cf6a-aedb-11e5-84a6-9aa3ad427988.png)

**Comment by candrawaskito** [comment]
ini juga, dibiasakan jangan di mention kalau untuk issue yang personal, di assign saja dan di kasih label @fadlillahayu 

<img width="269" alt="screen shot 2015-12-30 at 10 12 51 am" src="https://cloud.githubusercontent.com/assets/4866343/12045831/13ea26da-aede-11e5-8399-1e0d60115024.png">

**Comment by fadlillahayu** [comment]
kemaren udah nyoba tapi gak bisa, katanya karena gak dikasih hak akses buat nambahin assign dan label.. jadi dari kemaren yang nambahin assign dan label @nurmanhabib

**Comment by candrawaskito** [comment]
coba lagi, udah aku kasih hak akses

**Comment by fadlillahayu** [comment]
oke sudah @candrawaskito

**Comment by ahsansandiah** [comment]
oke otewe perbaikan.

**Comment by fadlillahayu** [comment]
oke yang ini sudah diperbaiki
