### ISSUE TITLE
Margin navbar-nav, font-weight and color, very2 important for this

### ISSUE THREAD

**Issue by candrawaskito** [amteknologi/elearning#223]
margin navbar nav untuk top kurang itu, tapi jangan pake margin-top, pakai line-heght aja, biar auto untuk top dan bottom nya, sama font-weight nya kurang tebel, terus bukannya kemarin warnanya juga tak suruh ganti ke #909090 

ASAP

<img width="308" alt="screen shot 2015-12-30 at 10 00 09 am" src="https://cloud.githubusercontent.com/assets/4866343/12045751/5f8bba06-aedc-11e5-83e4-74ed290b83fd.png">

**Comment by fajarekos** [comment]
![navbar](https://cloud.githubusercontent.com/assets/10874434/12045827/ed0c581c-aedd-11e5-8669-670fcd12c186.PNG)

segitu apa masih kurang tebal untuk font weight

**Comment by candrawaskito** [comment]
kurang, dan warnanya juga diganti @fajarekos

**Comment by fajarekos** [comment]
![font weight](https://cloud.githubusercontent.com/assets/10874434/12046042/3a3b4c8e-aee2-11e5-8b35-b548f6a17f65.PNG)

seperti ini sudah?

**Comment by candrawaskito** [comment]
Closed with references #206
