### ISSUE TITLE
Font-size title tab

### ISSUE THREAD

**Issue by candrawaskito** [amteknologi/elearning#226]
Untuk font-size tolong disamakan dengan title font-size yang lainnya.

<img width="248" alt="screen shot 2015-12-30 at 10 07 09 am" src="https://cloud.githubusercontent.com/assets/4866343/12045792/3944faa0-aedd-11e5-917e-519bf136d5e3.png">

**Comment by fajarekos** [comment]
![warna tabs](https://cloud.githubusercontent.com/assets/10874434/12046013/9a520db6-aee1-11e5-8d06-a46dbe324041.PNG)

warna itu awalnya emang sengaja beda atau disamain saja?

**Comment by candrawaskito** [comment]
oke #230
