### ISSUE TITLE
FAQ : tambah kolom title dan update time create faq

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#227]
pada form tambah FAQ di halaman admin tambahin kolom title, dan kenapa time create pada saat menambahkan faq di halaman admin tidak terupdate -> pada gambar di nomer 2 sedangkan jika menambahkan faq pada halaman dashboard faq akan terupdate time create nya -> pada gambar di nomer 1 :sweat_smile: @radhianPrayogo 

![beda admin dan sistem](https://cloud.githubusercontent.com/assets/16249496/12045780/5d520240-ae5f-11e5-9611-d7ae28e48e6c.png)

**Comment by candrawaskito** [comment]
jangan di mention, tapi di assignment saja, sama label nya di kasih. @YeyenMPJ 

<img width="269" alt="screen shot 2015-12-30 at 10 12 51 am" src="https://cloud.githubusercontent.com/assets/4866343/12045824/e9bb23f0-aedd-11e5-9414-e7b1224158ea.png">

**Comment by YeyenMPJ** [comment]
ga bisa nambahin label sama assignee. katanya ga di kasih hak akses gitu. kemaren juga udah nyoba tapi ga bs @candrawaskito

**Comment by candrawaskito** [comment]
oh oke, sekarang di coba lagi @YeyenMPJ

**Comment by YeyenMPJ** [comment]
oke sudah @candrawaskito

**Comment by radhianPrayogo** [comment]
#237 udah diperbaiki mbak @YeyenMPJ
