### ISSUE TITLE
For all page, change detail with new design

### ISSUE THREAD

**Issue by candrawaskito** [amteknologi/elearning#228]
Untuk semua page, yang html tolong disesuaikan ya semuanya, biar sama dengan desain index portal. Karena untuk dokumentasi juga
Contohnya di single.html yang ada di public/portal/single.html itu di sesuaikan dengan navbar yang baru.
Berlaku juga dengan page2 yang lain 

<img width="1168" alt="screen shot 2015-12-30 at 10 09 31 am" src="https://cloud.githubusercontent.com/assets/4866343/12045813/934d8896-aedd-11e5-8849-760de4c41596.png">

**Comment by fajarekos** [comment]
yang ini sudah tak ganti, tdi ikut ke pull request yang transition pada border belum di merge

**Comment by candrawaskito** [comment]
oke i will check it first

**Comment by candrawaskito** [comment]
untuk warna backgroundnya di ganti ke warna putih aja, keliatan jelek

<img width="1334" alt="screen shot 2015-12-30 at 10 25 09 am" src="https://cloud.githubusercontent.com/assets/4866343/12045917/ab04621e-aedf-11e5-9cc3-1de817ec3a6d.png">

**Comment by fajarekos** [comment]
kalo di samain warna navbarnya jadi mati mas

![warna nabvar mati](https://cloud.githubusercontent.com/assets/10874434/12045980/f04aa2b0-aee0-11e5-8adb-b7ffd40f48c7.PNG)

**Comment by candrawaskito** [comment]
bukan warna navbarnya yang ikut ma warna background, tapi warna background header nya yag di samain ma warna navbarnya, coba di baca lagi deh https://github.com/amteknologi/elearning/issues/228#issuecomment-167930329 @fajarekos
