### ISSUE TITLE
ELib :Gagal Upload ELib Halaman Depan

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#232]
Gagal upload media dihalaman depan : http://localhost/elearning/elibrary/media/submit
![fireshot screen capture 049 - portal - desa membangun - localhost_elearning_elibrary_media_submit](https://cloud.githubusercontent.com/assets/16182401/12046209/f7cd9178-aee5-11e5-830f-17901a7adbf3.png)

**Comment by radhianPrayogo** [comment]
udah ngisi data metanya belum?

**Comment by fadlillahayu** [comment]
belum @radhianPrayogo, harusnya kan biar udah diisi atau belum tampilanya tidak rusak seperti itu kan? itu karena gak ada folder medianya tau gimana, makanya jadi error kayak gitu?

**Comment by fadlillahayu** [comment]
oke, yang in udah diperbaiki
