### ISSUE TITLE
ELib : Tombol Save 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#241]
Tombol Savenya jangan terlalu mepet kebawah, keatasin lagi biar enak dilihat
![fireshot screen capture 055 - submit i elibrary - localhost_elearning_admin_elibrary_submit](https://cloud.githubusercontent.com/assets/16182401/12060754/f3d38140-afa8-11e5-9214-9ede7681a2a4.png)

**Comment by ahsansandiah** [comment]
udah aku perbaiki ada direquest  #247 tinggal tunggu dimarged.

**Comment by fadlillahayu** [comment]
oke, yang ini sudah
