### ISSUE TITLE
Elib : Search File/Media

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#244]
Ketika search berdasarkan kategori atau meta harusnya muncul list berdasarkan kategori/meta yang dipilih bukan tampilan kosong.
![fireshot screen capture 062 - portal - desa membangun - localhost_elearning_elibrary_search_q category 2 meta 0](https://cloud.githubusercontent.com/assets/16182401/12061066/564ff37a-afaf-11e5-883a-f0aa0f6e3a85.png)

**Comment by radhianPrayogo** [comment]
fungsi search udah diperbaiki disini #240 mbak @fadlillahayu

**Comment by fadlillahayu** [comment]
Ini coba searchnya jangan terlalu kekiri, taroh ditengah aja biar lebih enak dilihat @radhianPrayogo 
![fireshot screen capture 070 - portal - desa membangun - localhost_elearning_elibrary_search_q git category 11](https://cloud.githubusercontent.com/assets/16182401/12062644/f1efcfa8-afd2-11e5-9138-b7d292c6ed0e.png)
