### ISSUE TITLE
Forum : Pagination

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#245]
Paginationnya diperbaiki ya
![fireshot screen capture 054 - portal - desa membangun - localhost_elearning_forum](https://cloud.githubusercontent.com/assets/16182401/12061092/1d4f6ef6-afb0-11e5-8703-ce5006453bd7.png)

**Comment by radhianPrayogo** [comment]
bentar ya mbak @fadlillahayu , yang ini aku cuma make templatenya habib untuk tampilan paginationnya. untuk letak paginationnya nunggu mergeran

**Comment by fadlillahayu** [comment]
oke @radhianPrayogo

**Comment by candrawaskito** [comment]
ini kayaknya sudah resolved ya di #277 , bener gak @nurmanhabib

**Comment by candrawaskito** [comment]
Closed issue #277

**Comment by fadlillahayu** [comment]
belum kak @candrawaskito, masih ada yang kurang ditampilannya
![fireshot screen capture 101 - portal - desa membangun - localhost_elearning_forum](https://cloud.githubusercontent.com/assets/16182401/12083163/37cd261a-b2d0-11e5-8d38-453bfdac0292.png)
dan sedang dikerjakan sama @radhianPrayogo

**Comment by candrawaskito** [comment]
sudah, coba di pull lagi @fadlillahayu

**Comment by fadlillahayu** [comment]
oke sudah @candrawaskito
