### ISSUE TITLE
Elib : Error Page Upload File Big Size

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#249]
Error ketika upload file yang terlalu besar seharunya dalam bentuk notifikasi bukan error page.
link : http://localhost/elearning/admin/elibrary/submit
![fireshot screen capture 067 - - localhost_elearning_admin_elibrary_submit](https://cloud.githubusercontent.com/assets/16182401/12061932/3a144740-afc5-11e5-9533-2392c0ab8e5c.png)

**Comment by ahsansandiah** [comment]
udah diperbaiki tinggal dimerged. jangan lupa jga setting di php.ini jadi 20M 
'upload_max_filesize
'post_max_size'
