### ISSUE TITLE
Elib : Submit Dashboard

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#262]
Submit Elibrary dihalaman dashboard, disesuaikan ya @radhianPrayogo @ahsansandiah 
![fireshot screen capture 071 - portal - desa membangun - localhost_elearning_dashboard](https://cloud.githubusercontent.com/assets/16182401/12063379/68e513d6-afe0-11e5-8df2-669b6f11cc06.png)

**Comment by ahsansandiah** [comment]
udah dibuat tinggal dimarged

**Comment by fadlillahayu** [comment]
okay sudah
