### ISSUE TITLE
Konsultasi : Submit Konsultasi Dashboard

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#263]
Submit konsultasi dihalaman dashboard, disesuaikan ya 
![fireshot screen capture 072 - portal - desa membangun - localhost_elearning_dashboard](https://cloud.githubusercontent.com/assets/16182401/12063404/bdb34b9e-afe0-11e5-964c-4321e10ff3fe.png)

**Comment by candrawaskito** [comment]
Itu di rename ya..bukan kontent artikel tapi kontent konsultasi

**Comment by ahsansandiah** [comment]
udah di marged. silahkan ditesting

**Comment by ahsansandiah** [comment]
@fadlillahayu   mbak dillah ini jangan lupa di close kalo udah

**Comment by YeyenMPJ** [comment]
oke sudah
