### ISSUE TITLE
Portal : Error Link Kirim Artikel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#266]
Ini link submit artikel dihalaman public kenapa jadi gak bisa ya?
![fireshot screen capture 081 - - localhost_elearning_submitarticle](https://cloud.githubusercontent.com/assets/16182401/12070487/1346d192-b0aa-11e5-82d5-fb2cf7e6997c.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu Oh anu mbak, aku nambahin kolom baru, silahkan migrate ulang:

    $ ./phinx migrate -c phinx_portal.php

**Comment by fadlillahayu** [comment]
oke
