### ISSUE TITLE
Kelas : Button Finish

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#267]
button finish belum bisa
![finis](https://cloud.githubusercontent.com/assets/16182401/12070602/862303a0-b0b1-11e5-9de0-36e0586e7b3c.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu kemarin sudah saya perbaiki di #261 coba di pull lagi, kalo masih bermasalah nanti bs screenshoot di inspect element bagian console?

**Comment by fadlillahayu** [comment]
yang ini @nurmanhabib 
![finish1](https://cloud.githubusercontent.com/assets/16182401/12073322/5429f25a-b14c-11e5-8230-526f45c38699.png)

**Comment by nurmanhabib** [comment]
Oh iya lupa, itu aku nambahin package baru. Ikuti langkah berikut.
    $ cd public    $ npm install

Sent from Yahoo Mail on Android 
 
  On Sab, Jan 2, 2016 at 12:29, Fadlillah Mukti Ayudewi<notifications@github.com> wrote:   
yang ini @nurmanhabib
