### ISSUE TITLE
Elearning : All Thumb 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#268]
All Thumb Jangan lupa diganti Desa Membangun ya @nurmanhabib @singgihsap 
![fireshot screen capture 085 - portal - desa membangun - localhost_elearning](https://cloud.githubusercontent.com/assets/16182401/12070628/472d2330-b0b4-11e5-964a-8c1b62b327d2.png)

**Comment by singgihsap** [comment]
sudah diperbaiki mba @fadlillahayu di pull request #282

**Comment by fadlillahayu** [comment]
oke.. tunggu dimerge ya @singgihsap

**Comment by candrawaskito** [comment]
Closed at #282
