### ISSUE TITLE
Portal : Spasi Button Komentar Halaman Admin

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#269]
Pada halaman komentar draf antara button moderasi dan button hapus dikasih spasi, begitu juga dengan button edit dan button hapus pada halaman approve.
![fireshot screen capture 086 - comment - localhost_elearning_admin_comment](https://cloud.githubusercontent.com/assets/16182401/12070673/0790babe-b0b6-11e5-8da6-918695bdefcc.png)
![fireshot screen capture 087 - comment - localhost_elearning_admin_comment_status draft](https://cloud.githubusercontent.com/assets/16182401/12070674/08830ecc-b0b6-11e5-929d-3ce4d3f990bf.png)

**Comment by candrawaskito** [comment]
Itu bukan spasi..tapi margin.. Kasih ke Singgih aja @singgihsap

**Comment by candrawaskito** [comment]
ASAP ya, cuma nambahin margin doank @singgihsap

**Comment by singgihsap** [comment]
mas @candrawaskito aku edit pake width pada tablenya ggp kah ? bila ada kasus artikel itu panjang nanti table button sama tanggal di bikin fix gmna mas ?

**Comment by singgihsap** [comment]
di pull request ini #287 mas @candrawaskito

**Comment by candrawaskito** [comment]
itu ada comments di pull requestnya, di benerin dulu aja @singgihsap
