### ISSUE TITLE
Button browse pada tambah avatar dan fitur 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#270]
Button browse pada tambah avatar dan fitur pada tambah artikel dihalaman public dan halaman register tidak berfungsi. Jangan lupa diperbaiki

![fireshot screen capture 080 - portal - desa membangun - localhost_elearning_submitarticle](https://cloud.githubusercontent.com/assets/16182401/12070680/79548e00-b0b6-11e5-89a8-940688cf9d59.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah diperbaiki di #291
