### ISSUE TITLE
Header Single Page Register

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#272]
Header single page pada halaman register seharusnya tetap seperti ini :
![fireshot screen capture 082 - portal - desa membangun - localhost_elearning_dashboard](https://cloud.githubusercontent.com/assets/16182401/12070689/1355ada4-b0b7-11e5-8fec-2548b4f2e2f0.png)

Bukan : 
![fireshot screen capture 083 - portal - desa membangun - localhost_elearning_article_penundaan-penurunan-tunjangan-dana-desa](https://cloud.githubusercontent.com/assets/16182401/12070687/f33e6ce0-b0b6-11e5-90a9-1bb95e9a2276.png)

@nurmanhabib @fajarekos

**Comment by nurmanhabib** [comment]
@fadlillahayu kemarin ada rencana, klo yg udah login gabisa ke halaman home, apakah mau dibuat demikian? Jadi nanti yg udah login homepage nya itu ya dashboard mereka masing2.

**Comment by fadlillahayu** [comment]
apa gk dibuat seperti design view all nya artikel yg register aja @nurmanhabib ? biar headernya sama semua?

**Comment by nurmanhabib** [comment]
@fadlillahayu view all yang mana?

**Comment by fadlillahayu** [comment]
view all untuk artikel yg registered... kmren udah dibikin @fajarekos udah dipush blm ya @fajarekos ?

**Comment by candrawaskito** [comment]
untuk header single page untuk yang sudah login, tetep sama seperti header yang belum login, tetapi cuma ada perbedaan di kanan ada avatar user nya.

**Comment by fadlillahayu** [comment]
oh maaf baru nemu @candrawaskito @nurmanhabib @fajarekos 
kayak gini : 
![fireshot screen capture 089 - single portal - kemendesa - localhost_elearning_public_portal_single-dashboard-register_html](https://cloud.githubusercontent.com/assets/16182401/12072873/a2df097c-b12d-11e5-9661-a30643f708cd.png)
link : http://localhost/elearning/public/portal/single-dashboard-register.html

**Comment by fadlillahayu** [comment]
yang ini udah diperbaiki ya untuk header nya
![fireshot screen capture 090 - portal - desa membangun - localhost_elearning_dashboard_article_show_penundaan-penurunan-tunjangan-dana-desa](https://cloud.githubusercontent.com/assets/16182401/12072909/6dc2fd54-b130-11e5-9c0b-4f1e5cd10ef7.png)
