### ISSUE TITLE
Portal : Dropdown Kategori

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#281]
Dropdown kategori pada navbar belum jalan @nurmanhabib @fajarekos 
![bug dropdown](https://cloud.githubusercontent.com/assets/16182401/12082473/df29b28a-b2c5-11e5-83ba-85e8241a845a.PNG)
![dropdown blom tampil](https://cloud.githubusercontent.com/assets/16182401/12082481/ec39ee54-b2c5-11e5-8f48-aa94e8f29caf.PNG)

**Comment by candrawaskito** [comment]
@fadlillahayu buat issue nya dbedakan ya, yang satu @fajarekos dibuatkan issue sub nav untuk viewnya, nah si @nurmanhabib dibuatkan issue untuk logic nya, oke

**Comment by fadlillahayu** [comment]
okay @candrawaskito

**Comment by nurmanhabib** [comment]
sudah di #351 tapi tampilan masih kurang sip, sedang otw sama @fajarekos
