### ISSUE TITLE
Portal : Logic Dropdown Kategori (Public)

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#285]
Dropdown kategori pada navbar belum jalan
![bug dropdown](https://cloud.githubusercontent.com/assets/16182401/12083195/a32efdf2-b2d0-11e5-8f23-942289cfc10c.PNG)
![dropdown blom tampil](https://cloud.githubusercontent.com/assets/16182401/12083196/a3311ca4-b2d0-11e5-8351-850d60deabba.PNG)
![dropdown blom tampil](https://cloud.githubusercontent.com/assets/16182401/12083200/ae485d28-b2d0-11e5-93bd-3b27edcd49e9.PNG)

**Comment by nurmanhabib** [comment]
@fadlillahayu #351

**Comment by fadlillahayu** [comment]
belum ada linknya ya @nurmanhabib
