### ISSUE TITLE
Konsultasi : Tampilan

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#326]
Tampilan lihat konsultasi di halaman admin dirubah 

![lihat konsultasi di halaman admin](https://cloud.githubusercontent.com/assets/16249496/12165077/5bcff36a-b54d-11e5-97de-fbce8947b361.png)

**Comment by ahsansandiah** [comment]
mbak @YeyenMPJ udah aku perbaiki ada di #345 nunggu konfirmasi merged dari @nurmanhabib

**Comment by YeyenMPJ** [comment]
tampilannya kereeen :+1:
