### ISSUE TITLE
Konsultasi : Postingan 

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#327]
Konsultasi terbaru diletakkan paling atas

**Comment by ahsansandiah** [comment]
mbak @YeyenMPJ  udah aku perbaiki ada di #345 nunggu konfirmasi merged dari @nurmanhabib

**Comment by YeyenMPJ** [comment]
oke @ahsansandiah :+1:

**Comment by ahsansandiah** [comment]
@YeyenMPJ  mbak yen udah dimerged silahkan ditesting

**Comment by YeyenMPJ** [comment]
sip :+1:
