### ISSUE TITLE
Forum : Pagination 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#329]
paginationnya diseragamkan  
Link : http://localhost/elearning/forum/
![fireshot screen capture 137 - portal - desa membangun - localhost_elearning_forum](https://cloud.githubusercontent.com/assets/16182401/12165179/4a3ec6ca-b54e-11e5-8b94-3ec7fff72738.png)

Link : http://localhost/elearning/forum/topic
![fireshot screen capture 138 - portal - desa membangun - localhost_elearning_forum_topic](https://cloud.githubusercontent.com/assets/16182401/12165193/776946c0-b54e-11e5-91f7-2e3817f9ce9e.png)

dan pada navbar topik tenaga ahli dibuat paginationnya
Link : http://localhost/elearning/forum/topic/create

**Comment by radhianPrayogo** [comment]
udah diperbaiki, tinggal nunggu merger di pull request #344 @fadlillahayu

**Comment by fadlillahayu** [comment]
oke ditunggu @radhianPrayogo 
cc : @nurmanhabib yang ini dimerge ya
