### ISSUE TITLE
Forum : Alert Hapus

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#330]
untuk hapus categori, topik, dan thread ditambahin alert hapus (diadmin dan didashboard)

**Comment by radhianPrayogo** [comment]
sudah diperbaiki disini #357  mbak @fadlillahayu

**Comment by fadlillahayu** [comment]
Button Hapus Threadnya gak bisa @radhianPrayogo 
dan font untuk allert dikecilin, buttonnya juga besar kecilnya disamakan
![hapus](https://cloud.githubusercontent.com/assets/16182401/12188851/a1d6f02c-b5eb-11e5-9421-d64b81d9ac44.png)

**Comment by radhianPrayogo** [comment]
yang fungsi hapusnya udah tak push, kalo tampilannya di tempatku udah @fadlillahayu @singgihsap 
![draft](https://cloud.githubusercontent.com/assets/16092844/12192008/7e85de54-b60d-11e5-882a-f03b4fe619db.PNG)

**Comment by fadlillahayu** [comment]
allertnya dikecilin dan Button Hapus Threadnya gak bisa @radhianPrayogo

**Comment by radhianPrayogo** [comment]
tinggal nunggu di approve @fadlillahayu 
![modal](https://cloud.githubusercontent.com/assets/16092844/12195933/a3397f4c-b62d-11e5-9677-f6689c9cd0e8.PNG)
