### ISSUE TITLE
Elibrary : Preview Video Dashboard

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#331]
Ketika video diclose, video tidak mau berhenti, hanya tampilannya aja yang hilang (preview upload dan single)

**Comment by radhianPrayogo** [comment]
sudah diperbaiki di pull request #376 sama yang ambil kategori saat membuat thread juga udah disitu mbak @fadlillahayu

**Comment by fadlillahayu** [comment]
okay @radhianPrayogo
