### ISSUE TITLE
Dashboard Public : Pagination link informasi desa

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#333]
untuk view all link informasi desa dikasih pagination
Link : http://localhost/elearning/link

**Comment by nurmanhabib** [comment]
@fadlillahayu pastikan data lebih dari 20 untuk coba pagination

**Comment by fadlillahayu** [comment]
kayak gini @nurmanhabib 
![fireshot screen capture 151 - portal - desa membangun - localhost_elearning_link](https://cloud.githubusercontent.com/assets/16182401/12169359/8e08e9fa-b56a-11e5-9878-e7bd33876b39.png)
