### ISSUE TITLE
Dashboard Public : Reset pasword

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#334]
Reset Password dan Kategori artikel dihalaman reset password belum ada linknya.
Link : http://localhost/elearning/auth/login
![fireshot screen capture 139 - portal - desa membangun - localhost_elearning_auth_login](https://cloud.githubusercontent.com/assets/16182401/12165428/7eb0c096-b550-11e5-95f7-5286f5c1d6f7.png)

**Comment by ahsansandiah** [comment]
mbak @fadlillahayu ini aku testing ditempat ku udah jadi. monggo dicek lagi
