### ISSUE TITLE
Dashboard Public : Lupa pasword

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#335]
Lupa password  belum ada linknya.
Link : http://localhost/elearning/
 ![fireshot screen capture 140 - portal - desa membangun - localhost_elearning](https://cloud.githubusercontent.com/assets/16182401/12165467/bd5d954e-b550-11e5-9c9f-584a5161cad3.png)

**Comment by ahsansandiah** [comment]
@fadlillahayu ini udah aku ambil. dan udah aku tambahin ada di push request #452

**Comment by fadlillahayu** [comment]
pas masukin email muncul error : 
![fireshot screen capture 250 - - localhost_elearning_auth_reset](https://cloud.githubusercontent.com/assets/16182401/12316905/86b072aa-babe-11e5-8b88-1872c7c963a1.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu itu karna km belum `composer update`, karena ada package baru...

**Comment by ahsansandiah** [comment]
udah dimerged silahkan di composer update lagi. terus ditesting. tapi gunakan email yang valid

**Comment by fadlillahayu** [comment]
okay @nurmanhabib @ahsansandiah
