### ISSUE TITLE
Portal : Ukuran gambar/file/video pada artikel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#336]
Ukuran gambar/file/video  yang dilampirkan pada artikel belum ditampilkan dan belum dibatasi minimum dan maximumnya

**Comment by nurmanhabib** [comment]
@fadlillahayu ini yg kayak gmn ya kok bingung aku

**Comment by fadlillahayu** [comment]
otewe dijelaskan @nurmanhabib
