### ISSUE TITLE
Portal : All Kategori Halaman Private

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#338]
all kategori belum ada
![fireshot screen capture 145 - portal - desa membangun - localhost_elearning_dashboard_article](https://cloud.githubusercontent.com/assets/16182401/12165781/5d1271ca-b553-11e5-9f40-d8f58e7ebc4c.png)

**Comment by fadlillahayu** [comment]
ini tulisan All Categoriesnya gak kegedean kah? @fajarekos 
![fireshot screen capture 165 - portal - desa membangun - localhost_elearning_dashboard_article](https://cloud.githubusercontent.com/assets/16182401/12189096/973df5e6-b5ed-11e5-95be-2fe20d8dc232.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #374
