### ISSUE TITLE
Halaman Admin : Foto profile tidak bisa diganti

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#339]
![fireshot screen capture 146 - profile - localhost_elearning_admin_profile](https://cloud.githubusercontent.com/assets/16182401/12165847/cd719644-b553-11e5-81da-11cd33e67e80.png)

**Comment by nurmanhabib** [comment]
@ahsansandiah @fadlillahayu issu ini tak ambil alih ke @aku

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah selesai di #379
