### ISSUE TITLE
Halaman Admin : Media

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#340]
media belum ada linknya.
kemudian untuk upload nya dikasih batasan untuk minimum dan max gambar/file/video yang diupload
http://localhost/elearning/admin/media
![fireshot screen capture 147 - media - localhost_elearning_admin_media](https://cloud.githubusercontent.com/assets/16182401/12165872/05c571d2-b554-11e5-8f8e-c7eabd179e73.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #371
