### ISSUE TITLE
Halaman Admin : Page

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#341]
Page belum ada linknya.
http://localhost/elearning/admin/pages
![fireshot screen capture 148 - - localhost_elearning_admin_pages](https://cloud.githubusercontent.com/assets/16182401/12165894/32db4e3a-b554-11e5-8339-a67b2487e9b7.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #371
