### ISSUE TITLE
Halaman Admin : All button

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#342]
button pada halaman admin besar kecilnya disamakan seragamkan

**Comment by singgihsap** [comment]
sudah mba @fadlillahayu di pull request #358 , nanti kl ada yang kurang dicek lagi ya mba

**Comment by fadlillahayu** [comment]
yang dihalaman artikel belum
![fireshot screen capture 166 - edit i article - localhost_elearning_admin_article_edit_30](https://cloud.githubusercontent.com/assets/16182401/12189162/f8e76dea-b5ed-11e5-859a-4ff153d0ad1b.png)

dielibrary lihat juga belum. link http://localhost/elearning/admin/elibrary/edit/26 dan http://localhost/elearning/admin/elibrary/edit/28
![fireshot screen capture 168 - edit i elibrary - localhost_elearning_admin_elibrary_edit_26](https://cloud.githubusercontent.com/assets/16182401/12189240/919f17fe-b5ee-11e5-9042-25375076cc4f.png)

yang di kategori kelas online disejajarkan
![fireshot screen capture 167 - category i kelasonline - localhost_elearning_admin_kelasonline_category](https://cloud.githubusercontent.com/assets/16182401/12189222/6ec9eace-b5ee-11e5-960c-e5b2ad173dda.png)

**Comment by singgihsap** [comment]
sudah diperbaiki mbak @fadlillahayu dipull request #375

**Comment by fadlillahayu** [comment]
@singgihsap yang artikel kalo semuanya kecil, kecil semua termasuk yang corousel slider dan featured image

**Comment by fadlillahayu** [comment]
http://localhost/elearning/admin/elibrary/category/edit/15 
![fireshot screen capture 173 - edit i category i elibrary - 122_200_145_178_admin_elibrary_category_edit_4](https://cloud.githubusercontent.com/assets/16182401/12191392/e63e9dc6-b606-11e5-8cdb-e5aca1493078.png)

**Comment by singgihsap** [comment]
Sudah diperbaiki mba @fadlillahayu , di pull request #389 
monggo dicek lagi
