### ISSUE TITLE
Forum : Private Topik

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#349]
untuk private topiknya jangan lupa untuk yang all berdasarkan daerah segera dipush

**Comment by radhianPrayogo** [comment]
ini juga sudah diperbaiki disini #362 , nanti tinggal di cek aja @fadlillahayu

**Comment by fadlillahayu** [comment]
oke.. kurang yang tenaga ahli bisa input thread di topik dikelolanya ya

**Comment by radhianPrayogo** [comment]
yang ini juga udah tak perbaiki mbak @fadlillahayu :smile:
