### ISSUE TITLE
Responsive Navbar 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#350]
navbar kehidden sebelum discroll. 

gambar sebelum discroll 
![photo_2016-01-07_17-09-18](https://cloud.githubusercontent.com/assets/16182401/12167891/724c1ad8-b561-11e5-9ed9-2606bf52edc0.jpg)

gambar setelah discroll
![photo_2016-01-07_17-09-26](https://cloud.githubusercontent.com/assets/16182401/12167908/8a67df58-b561-11e5-863f-045fe23c3b23.jpg)

mungkin bisa dibantu @candrawaskito

**Comment by fajarekos** [comment]
@fadlillahayu ini sudah tinggal nunggu merge
