### ISSUE TITLE
Responsive dashboard

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#366]
navbar profilenya difullkan 
![fireshot screen capture 157 - portal - desa membangun - localhost_elearning_dashboard](https://cloud.githubusercontent.com/assets/16182401/12188283/4ada1cf4-b5e6-11e5-8cab-5de7bb6e7d2d.png)

**Comment by fajarekos** [comment]
nunggu merge @fadlillahayu

**Comment by fadlillahayu** [comment]
okesipp @fajarekos
