### ISSUE TITLE
Halaman Admin : Pagination

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#378]
tambah pagination halaman admin untuk :
1. artikel-kategori
2. kelas online-category
3. elibrary-elibary
4. elibrary-pengampu
5. konsutasi-pengampu
6. forum-kategori
7. faq

**Comment by ahsansandiah** [comment]
yang udah

- kelas online-category 
- elibrary-elbirary
- faq

**Comment by fadlillahayu** [comment]
berarti kurang yang forum dan artikel-kategori ya @ahsansandiah @radhianPrayogo
