### ISSUE TITLE
Portal : Input Artikel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#397]
tombol justifynya dihidden supaya artikel hanya bisa rata kiri

**Comment by fadlillahayu** [comment]
yang didasboard register belum @nurmanhabib 
![fireshot screen capture 186 - portal - desa membangun - localhost_elearning_dashboard](https://cloud.githubusercontent.com/assets/16182401/12226138/eed2781e-b849-11e5-9688-5555483b42fc.png)
link : http://localhost/elearning/dashboard

**Comment by nurmanhabib** [comment]
@fadlillahayu tp yg lain udah kan? Ya bntr yaa

**Comment by fadlillahayu** [comment]
yang dihalaman admin juga belum @nurmanhabib 
http://localhost/elearning/admin/article/add
![fireshot screen capture 192 - add i article - localhost_elearning_admin_article_add](https://cloud.githubusercontent.com/assets/16182401/12226547/60fac7ba-b850-11e5-87e4-f1eaa804fe3f.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #487

**Comment by fadlillahayu** [comment]
yang dihalaman admin belum @nurmanhabib

**Comment by fadlillahayu** [comment]
oh sudah.. sorry tadi belum keganti @nurmanhabib
