### ISSUE TITLE
Portal : Featured Image dan Carousel Slider

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#398]
Untuk foto/gambar ditambah keterangan foto

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #492

**Comment by fadlillahayu** [comment]
@nurmanhabib untuk yang artikel dihalaman public keterangan gambar belum ada. Kemudian untuk artikel yang dihalaman private/registered keterangan gambar yang muncul tidak sesuai dengan keterangan gambar yang dimasukkan.  berikut capturenya : 

Input Artikel public dari halaman admin
![fireshot screen capture 254 - edit i article - localhost_elearning_admin_article_edit_30](https://cloud.githubusercontent.com/assets/16182401/12344228/becdbf76-bb6d-11e5-8661-5d4678fefb56.png)

Tampak Single Artikel Halaman Public
![fireshot screen capture 255 - portal - desa membangun - localhost_elearning_article_nyobain-keterangan-gambar-public](https://cloud.githubusercontent.com/assets/16182401/12344236/d28aa150-bb6d-11e5-901c-100d1e98b715.png)

Input Artikel Private dari halaman admin
![fireshot screen capture 256 - edit i article - localhost_elearning_admin_article_edit_31](https://cloud.githubusercontent.com/assets/16182401/12344409/38b8783e-bb6f-11e5-9380-f9cd420b8848.png)

Tampak  Single Artikel Halaman Private
![fireshot screen capture 257 - portal - desa membangun - localhost_elearning_dashboard_article_show_nyobain-keterangan-gambar-private](https://cloud.githubusercontent.com/assets/16182401/12344422/5cecfba8-bb6f-11e5-8746-0c6a04f9da9c.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah dipperbaiki mbak #499

**Comment by fadlillahayu** [comment]
okay
