### ISSUE TITLE
Forum : Add Topic (data wilayah)

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#422]
Data Wilayahnya gak ngeload.
link : http://localhost/elearning/forum/topic/create
![fireshot screen capture 187 - portal - desa membangun - localhost_elearning_forum_topic_create](https://cloud.githubusercontent.com/assets/16182401/12226155/40ba6592-b84a-11e5-89a5-cb940dc7271e.png)

**Comment by radhianPrayogo** [comment]
yang ini juga udah diperbaiki, tunggu mergeran darisini #424 mbak @fadlillahayu
