### ISSUE TITLE
Forum : add thread

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#423]
Kategori yang sama muncul dua kali
link : http://localhost/elearning/forum/thread/create
![untitleds](https://cloud.githubusercontent.com/assets/16182401/12226174/baa0edcc-b84a-11e5-97c7-a93b70ef5f68.png)

**Comment by radhianPrayogo** [comment]
udah diperbaiki juga, tunggu mergeran darisini #424 mbak @fadlillahayu
