### ISSUE TITLE
Forum : Menampilkan Thread

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#425]
Menampilkan Thread Berdasarkan Ketegori
![fireshot screen capture 191 - portal - desa membangun - localhost_elearning_forum](https://cloud.githubusercontent.com/assets/16182401/12226453/f378f398-b84e-11e5-95ca-b222836b30b2.png)

**Comment by radhianPrayogo** [comment]
udah diperbaiki, tunggu mergeran darisini #424 mbak @fadlillahayu
