### ISSUE TITLE
Kelas : Delete Kelas

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#426]
Deletenya kekecilan (Delete This Course)
![fireshot screen capture 197 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_edit_4](https://cloud.githubusercontent.com/assets/16182401/12228292/cc43e52c-b86b-11e5-8daa-7c2eea35c973.png)
link :  http://localhost/elearning/kelas-online/dashboard/course/edit/4

**Comment by singgihsap** [comment]
sudah diperbaiki di pull request #428

**Comment by singgihsap** [comment]
update dipull request #433 @fadlillahayu
