### ISSUE TITLE
Kelas : Button Update

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#427]
Button Updatenya tertalu besar, disesuaikan dengan drafnya
![fireshot screen capture 196 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_status draft](https://cloud.githubusercontent.com/assets/16182401/12228312/fa4c760a-b86b-11e5-83cf-5e5c7394496c.png)
link : http://localhost/elearning/kelas-online/dashboard?status=draft

**Comment by singgihsap** [comment]
sudah diperbaiki mba @fadlillahayu di pull request #428
