### ISSUE TITLE
Admin : Profile

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#431]
Button Select dan Deletenya disejajarin ya 
![fireshot screen capture 201 - profile - localhost_elearning_admin_profile](https://cloud.githubusercontent.com/assets/16182401/12252963/851e6c6e-b90e-11e5-9441-217218bfc567.png)
link : http://localhost/elearning/admin/profile

**Comment by singgihsap** [comment]
Sudah diperbaiki di pull request #435 
cc: @fadlillahayu
