### ISSUE TITLE
Admin : Button

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#434]
Button Update dan hapunya disejajarkan 
![fireshot screen capture 205 - edit i category i elibrary - localhost_elearning_admin_elibrary_category_edit_15](https://cloud.githubusercontent.com/assets/16182401/12253492/8a4709a4-b912-11e5-8678-e765fa604a84.png)
link  : http://localhost/elearning/admin/elibrary/category/edit/15

![fireshot screen capture 206 - edit i article - localhost_elearning_admin_article_edit_29](https://cloud.githubusercontent.com/assets/16182401/12253508/aa4f67be-b912-11e5-8e9b-5d8ada7f0068.png)
link : http://localhost/elearning/admin/article/edit/29
link : http://localhost/elearning/admin/article/edit/3

![fireshot screen capture 207 - edit i elibrary - localhost_elearning_admin_elibrary_edit_3](https://cloud.githubusercontent.com/assets/16182401/12253727/74c188aa-b914-11e5-8c63-542414dfbd6b.png)
link : http://localhost/elearning/admin/elibrary/edit/3
link : http://localhost/elearning/admin/elibrary/edit/17

![fireshot screen capture 208 - edit i category i elibrary - localhost_elearning_admin_elibrary_category_edit_15](https://cloud.githubusercontent.com/assets/16182401/12253622/85bba6d2-b913-11e5-94a0-21e02293b759.png)
link : http://localhost/elearning/admin/elibrary/category/edit/15

![fireshot screen capture 210 - create i user - localhost_elearning_admin_user_create](https://cloud.githubusercontent.com/assets/16182401/12253677/f49b3b58-b913-11e5-970e-59f3b1c6c9dd.png)
link : http://localhost/elearning/admin/user/create
link : http://localhost/elearning/admin/user/updateProfile/1

**Comment by singgihsap** [comment]
Sudah diperbaiki di pull request #435 
cc: @fadlillahayu

**Comment by fadlillahayu** [comment]
yang ini belum @singgihsap 
![fireshot screen capture 210 - create i user - localhost_elearning_admin_user_create](https://cloud.githubusercontent.com/assets/16182401/12253677/f49b3b58-b913-11e5-970e-59f3b1c6c9dd.png)
link : http://localhost/elearning/admin/user/create
link : http://localhost/elearning/admin/user/updateProfile/1

**Comment by singgihsap** [comment]
sudah diperbaiki kak @fadlillahayu di pull resquest #447

**Comment by fadlillahayu** [comment]
yang dikelas online masih
![fireshot screen capture 226 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12284016/da9dfb84-b9de-11e5-833c-ec6e06ed2f32.png)
![fireshot screen capture 227 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12284023/e513c9f4-b9de-11e5-8409-17bd459815d3.png)
link : http://localhost/elearning/kelas-online/dashboard/course/create

**Comment by singgihsap** [comment]
sudah lagi kak dipull reques #450 :dancer:
