### ISSUE TITLE
Kelas : Tabel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#443]
sebelum diisi konten
![fireshot screen capture 219 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12282992/664499cc-b9d5-11e5-8a72-3d14357a88e5.png)
http://localhost/elearning/kelas-online/dashboard/course/create

setelah diisi konten
![fireshot screen capture 220 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12283024/aee24922-b9d5-11e5-96a2-5f3af96f7dbe.png)
http://localhost/elearning/kelas-online/dashboard/course/create

**Comment by fadlillahayu** [comment]
itu maksudnya untuk tabelnya diperbaiki ya @singgihsap biar gak kepotong garis ditabelna

**Comment by singgihsap** [comment]
Sudah diperbaiki kak @fadlillahayu di pull request #450 :dancer:
