### ISSUE TITLE
Kelas : Create Exam

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#444]
Create Exam form nya kok jadi seperti ini ya, kemudian untuk jawabannya ketika diketikkan langsung hilang (gak ke save)
![fireshot screen capture 221 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12283080/2fb9cce6-b9d6-11e5-9c7c-a18e571dc17a.png)
link : http://localhost/elearning/kelas-online/dashboard/course/create

Questionnya juga gak muncul 
![fireshot screen capture 223 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12283243/53a4696c-b9d7-11e5-9815-ee2269590400.png)

link : http://localhost/elearning/kelas-online/dashboard/course/create

**Comment by nurmanhabib** [comment]
@fadlillahayu oh astaghfirullah ada yg kelupaan, kmrn ada yg aku ubah

**Comment by nurmanhabib** [comment]
solved #449 @fadlillahayu

**Comment by fadlillahayu** [comment]
formnya belum @nurmanhabib 
![fireshot screen capture 228 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_create](https://cloud.githubusercontent.com/assets/16182401/12284113/bdf19724-b9df-11e5-83a9-0b946924b73c.png)
