### ISSUE TITLE
Forum : Add Anggota

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#461]
Tampilan untuk Add anggota dipoles 
link : http://localhost/elearning/forum/thread/create
![fireshot screen capture 232 - portal - desa membangun - localhost_elearning_forum_thread_create](https://cloud.githubusercontent.com/assets/16182401/12289791/09886dea-ba10-11e5-958d-ff5961cfc5e0.png)

**Comment by singgihsap** [comment]
sudah diperbaiki kak @fadlillahayu , dipull request #475 :dancer:
