### ISSUE TITLE
Kelas : Quis dan Exam

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#462]
Tampilan untuk jawaban benarnya diperbaiki untuk quis dan exam
![untitledkelas](https://cloud.githubusercontent.com/assets/16182401/12289866/a6563b16-ba10-11e5-86b9-625dc594bcce.png)

**Comment by singgihsap** [comment]
sudah diperbaiki kak @fadlillahayu di pul pullan #472
