### ISSUE TITLE
Elibrary : Meta 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#463]
ketika membuat meta, setelah disave meta berubah jadi 0 dan rename, tetapi kadang ada yang normal
@ahsansandiah @radhianPrayogo

**Comment by radhianPrayogo** [comment]
ini di depan atau di admin mbak @fadlillahayu ?

**Comment by fadlillahayu** [comment]
didepan dan diadmin @radhianPrayogo

**Comment by ahsansandiah** [comment]
udah diperbaiki sama @radhianPrayogo  dan sudah dimerged. silahkan ditesting lagi

**Comment by YeyenMPJ** [comment]
oke
