### ISSUE TITLE
Elibrary : File Document

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#466]
file document selalu tidak dikenali (unknown)
@radhianPrayogo @ahsansandiah

**Comment by YeyenMPJ** [comment]
yang belum tinggal txt jadi nya excel
![txt jadi excel](https://cloud.githubusercontent.com/assets/16249496/12344667/8995c808-bb72-11e5-82c5-5a2ee00b901e.png)

**Comment by YeyenMPJ** [comment]
ZIP RAR jadi unknown
![zip rar unknown](https://cloud.githubusercontent.com/assets/16249496/12345090/18d2576c-bb77-11e5-8095-a565cd8561ce.png)

**Comment by ahsansandiah** [comment]
ini udah diperbaiki dan udah dimarged
