### ISSUE TITLE
Kelas : Create

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#469]
Button finis selalu menampilkan pesan error meskipun semua form udah diisi dan tidak muncul errornya dimana.
![untitledkelasonline](https://cloud.githubusercontent.com/assets/16182401/12290135/97f4d774-ba12-11e5-97ac-35ef1c7e7700.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu #508 sudah mbak

**Comment by fadlillahayu** [comment]
@nurmanhabib 
![untuk habib finis](https://cloud.githubusercontent.com/assets/16182401/12348433/fc2e46d4-bb99-11e5-806b-3bfe5c3debd2.jpg)

**Comment by nurmanhabib** [comment]
@fadlillahayu kelupaan itu setelah pull lakukan:

    $ ./phinx migrate -c phinx_kelas.php

**Comment by fadlillahayu** [comment]
oke sudah bib
