### ISSUE TITLE
Forum : View (Index)

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#470]
Tenagaahli melihat semua topik pada kategori yang dikelolanya. Tenagaahi hanya melihat topik yang diikutinya pada kategori yang dikelola oleh tenagaahli lain.

**Comment by radhianPrayogo** [comment]
tunggu mergeran dari sini #471 @fadlillahayu

**Comment by fadlillahayu** [comment]
count nya udah tapi viewnya belum @radhianPrayogo

**Comment by fadlillahayu** [comment]
oke yang ini sudah @radhianPrayogo
