### ISSUE TITLE
Kelas : Button 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#476]
Button Approve dan Kick nya disamain besar kecilnya
![fireshot screen capture 246 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_edit_10_member_status pending](https://cloud.githubusercontent.com/assets/16182401/12315823/171b61fe-bab2-11e5-9adb-349244b61311.png)
link : http://localhost/elearning/kelas-online/dashboard/course/edit/10/member?status=pending

**Comment by singgihsap** [comment]
sudah diperbaiki mba @fadlillahayu dicek di pull request #481 :dancer:
