### ISSUE TITLE
Kelas : Chapter

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#477]
Button Download tidak jalan dan nomornya seharusnya berbeda tiap baris, bukan 001 semua.
Login sebagai kader
![fireshot screen capture 248 - portal - desa membangun - localhost_elearning_kelas-online_course_showchapter_course-9-8_chapter-1](https://cloud.githubusercontent.com/assets/16182401/12315933/494b9e9a-bab3-11e5-9987-e83df14fd216.png)
link : http://localhost/elearning/kelas-online/course/showchapter/COURSE-9-8/chapter-1#

**Comment by fadlillahayu** [comment]
ketika didownload muncul error di : http://localhost/elearning/public/7/chapter_6/belajar%20bahasa%20inggris.txt
![fireshot screen capture 271 - 404 page not found - localhost_elearning_public_7_chapter_6_belajar bahasa inggris_txt](https://cloud.githubusercontent.com/assets/16182401/12381829/6ba212d0-bdc4-11e5-8a0f-1ea0ff8aed8a.png)

**Comment by fadlillahayu** [comment]
@nurmanhabib tampilan saat download file .txt
http://localhost/elearning/public/kelas-content/7/chapter_6/belajar%20bahasa%20inggris.txt
![fireshot screen capture 290 - - localhost_elearning_public_kelas-content_7_chapter_6_belajar bahasa inggris_txt](https://cloud.githubusercontent.com/assets/16182401/12407475/438085b8-be8a-11e5-8a69-88b2e0f7aecd.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #594
