### ISSUE TITLE
Kelas : Design 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#479]
Tampilan awal kelas untuk login sebagai kader dipoles
![fireshot screen capture 252 - portal - desa membangun - localhost_elearning_kelas-online_](https://cloud.githubusercontent.com/assets/16182401/12317253/03291000-bac2-11e5-881f-28373e43d712.png)

**Comment by singgihsap** [comment]
sudah dipoles mba @fadlillahayu , dipull request #486
