### ISSUE TITLE
Forum : Tambah CSS

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#480]
Tambah CSS blockquote.
Quote Replynya diibaratin seperti yang dibawah ya
![fireshot screen capture 253 - portal - desa membangun - localhost_elearning_forum_thread_view_33](https://cloud.githubusercontent.com/assets/16182401/12317495/77ac2708-bac4-11e5-932b-721f3cc3e00d.png)
link : http://localhost/elearning/forum/thread/view/33

**Comment by singgihsap** [comment]
udah dipoles mba @fadlillahayu , bisa dicek di pull request #498
