### ISSUE TITLE
Portal : Beralih akun login

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#505]
Ketika memilih salah satu artikel pilihan, maka akan ditujukan ke halaman depan. Ketika pilih menu home, user bisa login dengan akun yang berbeda

**Comment by fadlillahayu** [comment]
ini filtering artikel pilihannya ya @YeyenMPJ @nurmanhabib 
*hanya note* nanti diperbaiki ya @nurmanhabib

**Comment by nurmanhabib** [comment]
aku ga paham

**Comment by YeyenMPJ** [comment]
yg ini inget? @nurmanhabib 
![gapaham](https://cloud.githubusercontent.com/assets/16249496/12378273/6505e3f6-bd6b-11e5-9597-dd1ebcbbbe14.png)

**Comment by YeyenMPJ** [comment]
filtering nya udah @nurmanhabib tp nampilinnya malah ke dashboard bukan ke artikel yang dipilih

**Comment by ahsansandiah** [comment]
ini udah aku ambil mbak @YeyenMPJ  dan mbak @fadlillahayu
