### ISSUE TITLE
Kelas : Finishing Quiz 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#513]
Quis setelah finish masih bisa quis lagi (sampai waktu habis) seharusnya kalau sudah finis tidak bisa ganti jawaban.

**Comment by nurmanhabib** [comment]
@fadlillahayu udah di #521 tapi setelah pull lakukan ini:

    $ ./phinx migrate -c phinx_kelas.php

**Comment by nurmanhabib** [comment]
udah diperbaiki #527
