### ISSUE TITLE
Portal : notifikasi 

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#514]
Tidak ada notifikasi saat kirim artikel jika ada elemen yang tidak diisi diform register dan admin

**Comment by ahsansandiah** [comment]
untuk yang didepan udah aku perbaiki mbak @YeyenMPJ # #530 
tinggal nunggu accept dari mas @nurmanhabib

**Comment by ahsansandiah** [comment]
mbak @YeyenMPJ  untuk admin udah aku perbaiki. dan udah dimerged silahkan ditest. dan confirm kembali kalo ada masalah
