### ISSUE TITLE
Dahboard : Button Change Password Profile 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#515]
disejajarkan ya
![fireshot screen capture 266 - portal - desa membangun - localhost_elearning_dashboard_changepassword](https://cloud.githubusercontent.com/assets/16182401/12348711/3682535a-bb9c-11e5-908d-add4dbfce1e3.png)
link : http://localhost/elearning/dashboard/changepassword

**Comment by singgihsap** [comment]
sudah diperbaiki mbak @fadlillahayu , di pull request #519
