### ISSUE TITLE
Admin : Change Password

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#516]
Error change password halaman admin
![fireshot screen capture 265 - - localhost_elearning_dashboard_changepassword](https://cloud.githubusercontent.com/assets/16182401/12348738/7f366d8e-bb9c-11e5-8b22-966eca45da6c.png)

**Comment by ahsansandiah** [comment]
mbak @fadlillahayu udah diperbaiki untuk change password halaman admin dan dashboard private silahkan di cek
