### ISSUE TITLE
Kelas : Dashboard Chapter 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#553]
http://localhost/elearning/kelas-online/course/chapter/COURSE-9-6
![fireshot screen capture 293 - portal - desa membangun - localhost_elearning_kelas-online_course_chapter_course-9-6](https://cloud.githubusercontent.com/assets/16182401/12407610/453fa522-be8b-11e5-883d-95dd485827ec.png)
profile instructornya dibenerin ya.. fotonya ditaroh ditengah, 
login : kader

**Comment by candrawaskito** [comment]
judul issue nya duplicated @fadlillahayu

**Comment by singgihsap** [comment]
sudah diperbaiki dipull request #556,
di cek mbak @fadlillahayu
