### ISSUE TITLE
Elib : edit elib

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#554]
simbol attachment nya di ketengahin ya :smile: 
![edit elib](https://cloud.githubusercontent.com/assets/16249496/12407710/3db49a5a-be8c-11e5-978b-4e0c9bf00ba0.png)

**Comment by singgihsap** [comment]
sudah diperbaiki mbak @YeyenMPJ :dancer: 
dipull request  #559

**Comment by YeyenMPJ** [comment]
siaaap
