### ISSUE TITLE
Kelas : Error Kategori

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#558]
Kategori kelasnya error
![fireshot screen capture 294 - portal - desa membangun - localhost_elearning_kelas-online_dashboard](https://cloud.githubusercontent.com/assets/16182401/12408165/274a56ac-be90-11e5-9b6b-9b51808db073.png)
link : http://localhost/elearning/kelas-online/dashboard
login sebagai : instructor

**Comment by nurmanhabib** [comment]
@fadlillahayu mbak coba pastikan sudah di migrate semua ya utk yg kelas.. oiya cek errornya jg pake inspect element, kali aja ada yg salah disana...

**Comment by fadlillahayu** [comment]
okay @nurmanhabib

**Comment by fadlillahayu** [comment]
jadi ini errornya, waktu kelasnya sudah dipublish,, kalo statusnya pending tampilannya normal

view saat status pending 
![fireshot screen capture 324 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_status draft](https://cloud.githubusercontent.com/assets/16182401/12502450/6620d33e-c0fb-11e5-8e5f-b5edd99a3a51.png)
link : http://localhost/elearning/kelas-online/dashboard?status=draft

view saat sudah publish 
![sidebar](https://cloud.githubusercontent.com/assets/16182401/12502486/e0f5842e-c0fb-11e5-9d6b-a36b6c1da564.png)

**Comment by fadlillahayu** [comment]
kayaknya masalah utamannya yang diadmin, 
jadi gini. saat diadmin statusnya draf, kontennya masih lengkap 
![fireshot screen capture 325 - course i kelasonline - localhost_elearning_admin_kelasonline_course_status draft](https://cloud.githubusercontent.com/assets/16182401/12502510/35490a64-c0fc-11e5-9fd6-eccb6c4fe7d8.png)

![fireshot screen capture 326 - edit i course i kelasonline - localhost_elearning_admin_kelasonline_course_edit_2](https://cloud.githubusercontent.com/assets/16182401/12502515/3f3c8fbe-c0fc-11e5-972d-5d872781fb56.png)


setelah disave and publish 
![fireshot screen capture 328 - edit i course i kelasonline - localhost_elearning_admin_kelasonline_course_edit_2_basic](https://cloud.githubusercontent.com/assets/16182401/12502523/51d14886-c0fc-11e5-9d4e-c784b7957dc2.png)
