### ISSUE TITLE
Kelas : Nama Kelas 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#560]
Nama Kelas Tidak Muncul didashoard, harusnya muncul 
![fireshot screen capture 295 - portal - desa membangun - localhost_elearning_kelas-online](https://cloud.githubusercontent.com/assets/16182401/12408294/96f1ceb2-be91-11e5-8946-d95031ddd9e4.png)
link : http://localhost/elearning/kelas-online/
login : kader

**Comment by nurmanhabib** [comment]
@fadlillahayu coba cek di database judulnya ke save ga

**Comment by fadlillahayu** [comment]
judulnya gak kesave @nurmanhabib

**Comment by nurmanhabib** [comment]
@fadlillahayu sambil di cek pake inspect element, biar bisa tau errornya apa

**Comment by fadlillahayu** [comment]
![nama kelas](https://cloud.githubusercontent.com/assets/16182401/12502353/50120a3c-c0fa-11e5-8942-a211a1c86f8f.png)
