### ISSUE TITLE
Kelas : Error Sidebar

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#561]
![fireshot screen capture 296 - portal - desa membangun - localhost_elearning_kelas-online_course_show_course-9-9-002](https://cloud.githubusercontent.com/assets/16182401/12408340/13f26d36-be92-11e5-99de-3bc8b2a5c725.png)
link : http://localhost/elearning/kelas-online/course/show/COURSE-9-9-002
login : kader

**Comment by nurmanhabib** [comment]
@fadlillahayu itu karna gapunya kategori, kan skrg dah dikasih validasi klo blm pilih kategori gbisa submit

**Comment by fadlillahayu** [comment]
yg baru dibuat juga @nurmanhabib

**Comment by fadlillahayu** [comment]
![sidebar](https://cloud.githubusercontent.com/assets/16182401/12502375/97fa9ed6-c0fa-11e5-8827-6271c14da1e7.png)
