### ISSUE TITLE
Kelas : Update 

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#562]
Ketika update kelas, nama dan deskripsinya hilang, harusnya tetap ada
![fireshot screen capture 297 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_edit_19](https://cloud.githubusercontent.com/assets/16182401/12408385/87fee90c-be92-11e5-9af2-5bed1b4e8668.png)
link : http://localhost/elearning/kelas-online/dashboard/course/edit/19
login : instructor

**Comment by nurmanhabib** [comment]
@fadlillahayu diperjelas mbak, coba cek di databasenya ada apa tidak datanya..

**Comment by fadlillahayu** [comment]
didatabase course : 
![fireshot screen capture 305 - localhost _ 127_0_0_1 _ elearning_kelas _ courses i phpmyadmin 4_5_1 - localhost_phpmyadmin_sql_php_server 1 db elear](https://cloud.githubusercontent.com/assets/16182401/12419294/b95b5256-bee7-11e5-83c4-9318522f7b57.png)

**Comment by fadlillahayu** [comment]
yang tak lingkarin ini, yang coursenya tak buat contoh di atas @nurmanhabib : 
![kelascourse](https://cloud.githubusercontent.com/assets/16182401/12419379/376a91c0-bee8-11e5-87ef-529927250769.png)
