### ISSUE TITLE
Kelas : Delete Requirement

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#566]
Ketika requirement didelete kemudian disave, requirement tidak hilang(tidak kehapus), seharusnya kehapus,

tampak requirement : 
![photo_2016-01-19_11-52-21](https://cloud.githubusercontent.com/assets/16182401/12410029/4b113dd6-bea3-11e5-90b0-945da29d460f.jpg)

requirement dihapus : 
![photo_2016-01-19_11-52-33](https://cloud.githubusercontent.com/assets/16182401/12410048/74b0523a-bea3-11e5-802e-42e7483394f0.jpg)

setelah disave : 
![photo_2016-01-19_11-52-21](https://cloud.githubusercontent.com/assets/16182401/12410052/81724302-bea3-11e5-946d-c9dd5e96b538.jpg)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah di #574

**Comment by fadlillahayu** [comment]
okay close
