### ISSUE TITLE
Kelas : Member

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#567]
Kelas baru dibuat, dan belum ada member yang join, tetapi didalam member sudah ada satu member yang join dengan status pending
![fireshot screen capture 300 - portal - desa membangun - localhost_elearning_kelas-online_dashboard_course_edit_20_member_status pending](https://cloud.githubusercontent.com/assets/16182401/12410370/f0263f3a-bea6-11e5-81c0-d026ab1f36aa.png)
link : http://localhost/elearning/kelas-online/dashboard/course/edit/20/member?status=pending
login : instructor

**Comment by nurmanhabib** [comment]
@fadlillahayu lah gmn bisa begitu? mgkin pernah ke join mgkin, coba bkin baru lg apa akan seperti itu lg?

**Comment by fadlillahayu** [comment]
itu kelasnya baru tak bikin tadi @nurmanhabib , tanggal 19 januari.. tapi membernya joined at 18 januari.. ini lagi tak coba lagi untuk yang ini.
