### ISSUE TITLE
Server Portal : Edit (Tambah Keterangan Gambar)

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#579]
Ketika edit artikel dan  menambah  keterangan gambar, Keterangan gambar tidak tersimpan dan tidak muncul didepan (private-public). Begitu juga ketika melakukan edit keterangan gambar, setelah diedit dan disave keterangan gambar yang terimpan masih keterangan gambar lama, bukan keterangan gambar yang baru.
login : sebagai admin.

tambah keterangan gambar
![fireshot screen capture 313 - edit i article - 122_200_145_178_admin_article_edit_87](https://cloud.githubusercontent.com/assets/16182401/12438775/9001fc82-bf5c-11e5-897e-2bced4a05d7e.png)

setelah diupdate
![fireshot screen capture 314 - edit i article - 122_200_145_178_admin_article_edit_87](https://cloud.githubusercontent.com/assets/16182401/12438792/bf1ea060-bf5c-11e5-8a82-2086c3142f84.png)

view artikel private
![fireshot screen capture 315 - portal - desa membangun - 122_200_145_178_dashboard_article_show_philipus-brown-bongkar-tragedi-911-di-amerika-serika](https://cloud.githubusercontent.com/assets/16182401/12438803/e264f772-bf5c-11e5-8941-3050841883cb.png)

**Comment by nurmanhabib** [comment]
hmm sepertinya saya lupa blm buat yg bagian update jg ga ke save ya... oke segera diperbaiki (baru liat)

**Comment by nurmanhabib** [comment]
@fadlillahayu sudah diperbaiki #603 dan #602

**Comment by fadlillahayu** [comment]
oke.. tunggu yang diserver ya

**Comment by nurmanhabib** [comment]
#692 untuk yg public juga sudah
