### ISSUE TITLE
Server Portal : Reply Komentar Halaman Private

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#580]
Reply Komentar pada artikel halaman private belum bisa
![fireshot screen capture 316 - portal - desa membangun - 122_200_145_178_dashboard_article_show_buah-apel comments](https://cloud.githubusercontent.com/assets/16182401/12439055/20baed04-bf5f-11e5-80cc-43923806a0c4.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu bisa mbak atau mgkin ada plugins yg blm diinstall, coba npm install

**Comment by fadlillahayu** [comment]
diserver aku npm installnya dimananya @nurmanhabib ?
