### ISSUE TITLE
Server Portal : Komentar Terkini (Halaman Public)

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#582]
Komentar terkini masih menampilkan komentar pada artikel private

**Comment by nurmanhabib** [comment]
@fadlillahayu ini kan sudah dibenarin waktu sm mas @ahsansandiah  juga

**Comment by fadlillahayu** [comment]
iya dilocal udah bisa.. diserver yg blm bisa @nurmanhabib
