### ISSUE TITLE
Server Potal : Submit Artikel

### ISSUE THREAD

**Issue by fadlillahayu** [amteknologi/elearning#583]
Tampilan submit artikel rusak. 

Halaman Private (Registered)
Link : http://122.200.145.178/dashboard/sendArticle
![fireshot screen capture 308 - portal - desa membangun - 122_200_145_178_dashboard_sendarticle](https://cloud.githubusercontent.com/assets/16182401/12439438/2ab41200-bf63-11e5-95de-a45650cea0bf.png)

Halaman Public
![fireshot screen capture 318 - portal - desa membangun - 122_200_145_178_submitarticle](https://cloud.githubusercontent.com/assets/16182401/12439449/43d6d754-bf63-11e5-8680-81793ff19f3f.png)

**Comment by nurmanhabib** [comment]
@fadlillahayu kejadiannya kapan ya?

**Comment by fadlillahayu** [comment]
kemarin @nurmanhabib
