### ISSUE TITLE
Elibrary server

### ISSUE THREAD

**Issue by YeyenMPJ** [amteknologi/elearning#588]
preview audio tidak berhenti ketika di close

**Comment by ahsansandiah** [comment]
mbak  @YeyenMPJ udah diperbaiki #592

**Comment by YeyenMPJ** [comment]
iya tp di server belum yak @ahsansandiah :V

**Comment by YeyenMPJ** [comment]
@ahsansandiah tampilan review audio masih begini :cry: 
![icon review audio](https://cloud.githubusercontent.com/assets/16249496/12500637/a44e762a-c0e7-11e5-8382-17d1b1440608.png)
